apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-mini-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-mini-app
  template:
    metadata:
      labels:
        app: ai-mini-app
    spec:
      containers:
      - name: ai-mini-app
        image: anirudh30/ai-mini-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
